# Model arguments
model_name_or_path: kykim0/pythia-1b-tulu-v2-mix
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  kykim0/ultrafeedback_binarized_cleaned_20p: 1.0

dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: "no"
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: mistral-7b-instruct-sppo-iter1
learning_rate: 5.0e-7
log_level: info
logging_steps: 1
loss_type: rpo
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: checkpoints/mistral-7b-instruct-sppo-iter1
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 0.1
save_total_limit: 20
seed: 42
warmup_ratio: 0.1