# Model arguments
torch_dtype: bfloat16
load_in_8bit: false
model_name_or_path: kykim0/pythia-1b-tulu-v2-mix
sft_model_path: kykim0/pythia-1b-tulu-v2-mix
reward_model_path: kykim0/pythia-1b-tulu-v2-mix-uf-rm
# attn_implementation: flash_attention_2

# Data training arguments (2 devices assumed)
dataset_mixer:
  # HuggingFaceH4/ultrafeedback_binarized: 1.0
  kykim0/ultrafeedback_binarized_cleaned_20p: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# PPO arguments
# total_episodes: 15000
num_train_epochs: 1
num_ppo_epochs: 4
num_mini_batches: 1
per_device_train_batch_size: 1
per_device_eval_batch_size: 10
local_rollout_forward_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 3.0e-6
kl_coef: 0.05
response_length: 512
min_response_length: 16
non_eos_penalty: true
penalty_reward_value: -1
num_sample_generations: 10
output_dir: output/pythia-1b-pythia-1b-rm-pilot
log_level: info
logging_steps: 10
logging_strategy: steps
eval_steps: 0.1
eval_strategy: steps
report_to:
- wandb
# save_strategy: epoch
save_strategy: steps
save_steps: 0.05
save_total_limit: null
save_only_model: true
seed: 42
